### ISSUE TITLE
Data for Smarthome

### ISSUE THREAD

**Issue by 123gerald1** [awysocki/databox24#1]
Hello awysocki,
I operate my Smarthome via the software IoBroker.
Is it possible to transfer the data from the data box directly to the IoBroker via e.g. MQTT?
Or can I request them directly?
Thanks
Gerald

**Comment by awysocki** [comment]
Gerald,

I have never coded MQTT, but a quick look seems like it would be possible.  The sample code I wrote does a simple POST to a server with the data.  I'm sure it could be modified to use MQTT.  I currently don't have the time to code and test that.

Thanks
Andy
