### ISSUE TITLE
What exactly is "Device Status"

### ISSUE THREAD

**Issue by ButteredPotatos** [awysocki/databox24#3]
Hey,
I was just wondering what exactly the value "Device Status" is. 
Can someone help me?

**Comment by awysocki** [comment]
There is no field defined as Device Status,  Can you be more specific what you are looking at?  Post the structure you have the question on?

**Comment by awysocki** [comment]
If you are asking about

	0x43		- Header (1 byte)
	0xC0		- CMD - 0xC0=Device status (1 byte)	
	0x1122 		- Databox ID (2 bytes)
	0x0000		- Area ID (2 bytes) What is passed in is returned
	0x11223344	- Inverter ID (4 bytes)
	0x11223344	- Value Parameter (4 byte) 0x00=Status, 0x01=Turn ON, 0x02=Turn OFF, 0x03=Reboot
	0xCD		- Check Digit

0xC0 Device Status.  That is defined by the mfg of the unit.  The device will send a hex 0xC0 saying this data is device status.  They did not define or give me information for other Commands,  Its a received byte and the 0xC0 just says its status from the unit.
